name: Android-Cmake

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  # Customize the CMake build type here (Release, Debug, RelWithDebInfo, etc.)
  ANDROID_SDK_PATH: /usr/local/lib/android/sdk
  NDK_BUILD_TYPE: arm64-v8a
  NDK_PATH: /usr/local/lib/android/sdk/ndk
  #Github 的NDK安装有点毛病,只能指定 21.4.7075529, 而 NDK 最新的稳定版本 23.0.7599858
  NDK_VERSION: 21.4.7075529
  

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
     
    - name: Install NDK
      run: sudo ${{env.ANDROID_SDK_PATH}}/tools/bin/sdkmanager --install "ndk;${{env.NDK_VERSION}}" 
            
    - name: Configure CMake
      run: cmake -B ${{github.workspace}}/build   -DANDROID_ABI=${{env.NDK_BUILD_TYPE}} \
           -DCMAKE_TOOLCHAIN_FILE=${{env.NDK_PATH}}/${{env.NDK_VERSION}}/build/cmake/android.toolchain.cmake
          
    - name: CMake Build
      # Build your program with the given configuration
      run: cmake --build ${{github.workspace}}/build -DANDROID_ABI=${{env.NDK_BUILD_TYPE}} 
      
    - name: Pack artifact
      uses: actions/upload-artifact@v2
      with:
        name: ssocks
        path: ${{github.workspace}}/build
      
